#!/bin/bash

sudo apt install python3-dev python3-pip

pip install -U --user pip numpy wheel
pip install -U --user keras_preprocessing --no-deps

go get github.com/bazelbuild/bazelisk
export PATH=$PATH:$(go env GOPATH)/bin
alias bazel="bazelisk"

./configure
